### ISSUE TITLE
Create Python Dash dashboard

### ISSUE THREAD

**Issue by WraySmith** [ubco-mds-2020-labs/dashboard-project-group14#14]
Create basic functionality for Python Dash dashboard. Focus is on making everything in the proposal work, any major formatting can be done during Milestone 4 (unless time permits).

**Comment by RyKoe** [comment]
- [ ] Change chart one so that it contains all data with highlights
- [ ] Change second chart to stack chart that changes to monograph when too many categories
- [ ] Change filtering so that you can only select based off of categories, mechanics, or publishers
- [ ] Only have filtering allow to select max 5
- [ ] Change bottom graphs to have static axis and to sort via rating
